### ISSUE TITLE
ls: : No such file or directory wasn't matched

### ISSUE THREAD

**Issue by cmnybo** [sole/aafm#36]
When I run aafm it opens in /mnt/sdcard which is empty. The only thing that shows up is .. 
When I open that I get this:

```
EXECUTE= adb shell ls --help
BusyBox ls detected
EXECUTE= adb shell ls -l -A -e --color=never "/mnt/sdcard/"
EXECUTE= adb shell ls -l -A -e --color=never "/mnt/"
EXECUTE= adb shell ls -l -A -e --color=never "/"
EXECUTE= adb shell ls -l -A -e --color=never "/data"
ls: can't open '/data': Permission denied wasn't matched, please report to the developer!
EXECUTE= adb shell ls -l -A -e --color=never "/system"
EXECUTE= adb shell ls -l -A -e --color=never "bin"
EXECUTE= adb shell ls -l -A -e --color=never ""
ls: : No such file or directory wasn't matched, please report to the developer!
EXECUTE= adb shell ls -l -A -e --color=never ""
ls: : No such file or directory wasn't matched, please report to the developer!
EXECUTE= adb shell ls -l -A -e --color=never ""
ls: : No such file or directory wasn't matched, please report to the developer!
EXECUTE= adb shell ls -l -A -e --color=never ""
ls: : No such file or directory wasn't matched, please report to the developer!
EXECUTE= adb shell ls -l -A -e --color=never ""
ls: : No such file or directory wasn't matched, please report to the developer!
EXECUTE= adb shell ls -l -A -e --color=never ""
ls: : No such file or directory wasn't matched, please report to the developer!
EXECUTE= adb shell ls -l -A -e --color=never ""
ls: : No such file or directory wasn't matched, please report to the developer!
EXECUTE= adb shell ls -l -A -e --color=never ""
ls: : No such file or directory wasn't matched, please report to the developer!
EXECUTE= adb shell ls -l -A -e --color=never ""
ls: : No such file or directory wasn't matched, please report to the developer!
EXECUTE= adb shell ls -l -A -e --color=never ""
ls: : No such file or directory wasn't matched, please report to the developer!
EXECUTE= adb shell ls -l -A -e --color=never ""
ls: : No such file or directory wasn't matched, please report to the developer!
EXECUTE= adb shell ls -l -A -e --color=never ""
ls: : No such file or directory wasn't matched, please report to the developer!
EXECUTE= adb shell ls -l -A -e --color=never ""
ls: : No such file or directory wasn't matched, please report to the developer!
EXECUTE= adb shell ls -l -A -e --color=never ""
ls: : No such file or directory wasn't matched, please report to the developer!
EXECUTE= adb shell ls -l -A -e --color=never ""
ls: : No such file or directory wasn't matched, please report to the developer!
EXECUTE= adb shell ls -l -A -e --color=never ""
ls: : No such file or directory wasn't matched, please report to the developer!
EXECUTE= adb shell ls -l -A -e --color=never ""
ls: : No such file or directory wasn't matched, please report to the developer!
EXECUTE= adb shell ls -l -A -e --color=never ""
ls: : No such file or directory wasn't matched, please report to the developer!
EXECUTE= adb shell ls -l -A -e --color=never ""
ls: : No such file or directory wasn't matched, please report to the developer!
EXECUTE= adb shell ls -l -A -e --color=never ""
ls: : No such file or directory wasn't matched, please report to the developer!
EXECUTE= adb shell ls -l -A -e --color=never ""
ls: : No such file or directory wasn't matched, please report to the developer!
EXECUTE= adb shell ls -l -A -e --color=never ""
ls: : No such file or directory wasn't matched, please report to the developer!
EXECUTE= adb shell ls -l -A -e --color=never ""
ls: : No such file or directory wasn't matched, please report to the developer!
EXECUTE= adb shell ls -l -A -e --color=never ""
ls: : No such file or directory wasn't matched, please report to the developer!
EXECUTE= adb shell ls -l -A -e --color=never ""
ls: : No such file or directory wasn't matched, please report to the developer!
EXECUTE= adb shell ls -l -A -e --color=never ""
ls: : No such file or directory wasn't matched, please report to the developer!
EXECUTE= adb shell ls -l -A -e --color=never ""
ls: : No such file or directory wasn't matched, please report to the developer!
EXECUTE= adb shell ls -l -A -e --color=never ""
ls: : No such file or directory wasn't matched, please report to the developer!
EXECUTE= adb shell ls -l -A -e --color=never ""
ls: : No such file or directory wasn't matched, please report to the developer!
EXECUTE= adb shell ls -l -A -e --color=never ""
ls: : No such file or directory wasn't matched, please report to the developer!
EXECUTE= adb shell ls -l -A -e --color=never ""
ls: : No such file or directory wasn't matched, please report to the developer!
EXECUTE= adb shell ls -l -A -e --color=never ""
ls: : No such file or directory wasn't matched, please report to the developer!
EXECUTE= adb shell ls -l -A -e --color=never ""
ls: : No such file or directory wasn't matched, please report to the developer!
EXECUTE= adb shell ls -l -A -e --color=never ""
ls: : No such file or directory wasn't matched, please report to the developer!
EXECUTE= adb shell ls -l -A -e --color=never ""
ls: : No such file or directory wasn't matched, please report to the developer!
EXECUTE= adb shell ls -l -A -e --color=never ""
ls: : No such file or directory wasn't matched, please report to the developer!
EXECUTE= adb shell ls -l -A -e --color=never ""
ls: : No such file or directory wasn't matched, please report to the developer!
EXECUTE= adb shell ls -l -A -e --color=never ""
ls: : No such file or directory wasn't matched, please report to the developer!
EXECUTE= adb shell ls -l -A -e --color=never ""
ls: : No such file or directory wasn't matched, please report to the developer!
EXECUTE= adb shell ls -l -A -e --color=never ""
ls: : No such file or directory wasn't matched, please report to the developer!
EXECUTE= adb shell ls -l -A -e --color=never "/mnt"
EXECUTE= adb shell ls -l -A -e --color=never "/"
EXECUTE= adb shell ls -l -A -e --color=never "/data"
^CTraceback (most recent call last):
  File "aafm-gui.py", line 179, in device_navigate_callback
    self.refresh_device_files()
  File "aafm-gui.py", line 188, in refresh_device_files
    self.device_treeViewFile.load_data(self.dir_scan_device(self.device_cwd))
  File "aafm-gui.py", line 310, in dir_scan_device
    entries = self.aafm.get_device_file_list()
  File "/home/<username>/Desktop/aafm/src/Aafm.py", line 55, in get_device_file_list
    return self.parse_device_list( self.device_list_files( self._path_join_function(self.device_cwd, '') ) )
  File "/home/<username>/Desktop/aafm/src/Aafm.py", line 103, in parse_device_list
    is_directory = self.is_device_file_a_directory(target)
  File "/home/<username>/Desktop/aafm/src/Aafm.py", line 138, in is_device_file_a_directory
    entries = self.parse_device_list(lines)
  File "/home/<username>/Desktop/aafm/src/Aafm.py", line 103, in parse_device_list
    is_directory = self.is_device_file_a_directory(target)
  File "/home/<username>/Desktop/aafm/src/Aafm.py", line 138, in is_device_file_a_directory
    entries = self.parse_device_list(lines)
  File "/home/<username>/Desktop/aafm/src/Aafm.py", line 103, in parse_device_list
    is_directory = self.is_device_file_a_directory(target)
  File "/home/<username>/Desktop/aafm/src/Aafm.py", line 138, in is_device_file_a_directory
    entries = self.parse_device_list(lines)
  File "/home/<username>/Desktop/aafm/src/Aafm.py", line 103, in parse_device_list
    is_directory = self.is_device_file_a_directory(target)
  File "/home/<username>/Desktop/aafm/src/Aafm.py", line 137, in is_device_file_a_directory
    lines = self.device_list_files(parent_dir)
  File "/home/<username>/Desktop/aafm/src/Aafm.py", line 69, in device_list_files
    lines = self.execute(command)
  File "/home/<username>/Desktop/aafm/src/Aafm.py", line 36, in execute
    line = process.readline()
KeyboardInterrupt
```

It will repeat until I kill it. I can run the adb shell fine. There are no problems moving around and listing files, so I know my device is connected properly.
By the way I am using an Archos G9 101 Turbo 250GB with android 4.0.3
I am using Ubuntu 11.04 x64 and I have python version 2.7.1 installed.

**Comment by sole** [comment]
Something in the parsing might be wrong, but this will need a bit more of research from your side, as I can't experiment with your device from my keyboard :-P

**Comment by sole** [comment]
Could you try with latest versions? Are you using busy box or any custom rom?

Closing as per lack of comments from your side, feel free to reopen with info... :)
