### ISSUE TITLE
Inexistent gid causes crash

### ISSUE THREAD

**Issue by muflone** [sole/aafm#38]
My home folder is used by many installed GNU/Linux distributions, so some files could be have inexistent gid.

``` bash
$ ls -ld /home/common/Skype/
drwx------ 6 muflone 1000 4096 11 ago 00.49 /home/common/Skype/
$ getent group 1000
```

Such files cause aafm to crash:

``` bash
$ aafm

** (process:28033): WARNING **: Trying to register gtype 'GMountMountFlags' as enum when in fact it is of type 'GFlags'

** (process:28033): WARNING **: Trying to register gtype 'GDriveStartFlags' as enum when in fact it is of type 'GFlags'

** (process:28033): WARNING **: Trying to register gtype 'GSocketMsgFlags' as enum when in fact it is of type 'GFlags'
EXECUTE= adb shell ls --help
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/aafm/aafm-gui.py", line 803, in <module>
    gui = Aafm_GUI()
  File "/usr/lib/python2.7/site-packages/aafm/aafm-gui.py", line 141, in __init__
    self.refresh_host_files()
  File "/usr/lib/python2.7/site-packages/aafm/aafm-gui.py", line 183, in refresh_host_files
    self.host_treeViewFile.load_data(self.dir_scan_host(self.host_cwd))
  File "/usr/lib/python2.7/site-packages/aafm/aafm-gui.py", line 237, in dir_scan_host
    'group': self.get_group(path)
  File "/usr/lib/python2.7/site-packages/aafm/aafm-gui.py", line 297, in _get_group
    return grp.getgrgid(gid)[0]
KeyError: 'getgrgid(): gid not found: 1000'
```

Your app should gracefully handle unknown gid

**Comment by sole** [comment]
Fixed by @muflone ^_^
